import { Footer } from '@/app/components/footer';
import { Header } from '@/app/components/header';

import '@/app/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div className="flex min-h-screen flex-col items-center bg-white-1">
          <Header loginCheck={true} />
          <main className="w-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
